-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jul 28, 2021 at 10:44 PM
-- Server version: 5.7.24
-- PHP Version: 7.2.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `task-board`
--

-- --------------------------------------------------------

--
-- Table structure for table `card`
--

CREATE TABLE `card` (
  `id` int(11) NOT NULL,
  `title` varchar(1000) NOT NULL,
  `description` varchar(10000) NOT NULL,
  `label_title` varchar(100) NOT NULL,
  `label_color` varchar(50) NOT NULL,
  `list_title` varchar(255) NOT NULL,
  `card_id` varchar(100) NOT NULL,
  `card_order` int(11) NOT NULL,
  `list_id` varchar(50) NOT NULL,
  `due_date` varchar(255) DEFAULT NULL,
  `timestamp` varchar(255) DEFAULT NULL,
  `archive_id` varchar(50) NOT NULL DEFAULT '',
  `card_container_id` varchar(50) DEFAULT NULL,
  `create_date` varchar(60) DEFAULT NULL,
  `card_attachment` varchar(20000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `card`
--

INSERT INTO `card` (`id`, `title`, `description`, `label_title`, `label_color`, `list_title`, `card_id`, `card_order`, `list_id`, `due_date`, `timestamp`, `archive_id`, `card_container_id`, `create_date`, `card_attachment`) VALUES
(1, 'Card Generated By DBgfkiojsuioyfaegsfKLNKAsjd', 'new card generated by db and php', 'custom label 1', 'blue', 'Done', 'card-id-1', 0, 'list-4', '2021-07-30', '1627005118377', '', 'card-container-1', '2021-07-28 23:39PM', 'myimage.png,| task.csv,| exam.txt,| screenshot.png,| text.docx,| file.pdf,| myanimated.gif,| code.html,| somenote.csv,| animation1.gif,| mywordfile.docx,| knownfile.crt'),
(2, 'Card Generated By DB2', 'Card Generated By DB2 description', 'Important', 'darkblue', 'Done', 'card-id-2', 1, 'list-4', NULL, '1627005118377', '', 'card-container-2', '2021-07-28 23:39PM', 'myimage.png,| task.csv,| exam.txt,| screenshot.png'),
(3, 'Card Generated By DB3', 'Card Generated By DB3 description', 'Meeting', 'lightgreen', 'Pending', 'card-id-3', 0, 'list-3', NULL, '1627005118377', '', 'card-container-3', '2021-07-28 23:39PM', ''),
(4, 'Card Generated By DB4', 'Card Generated By DB4 description', 'Help', 'lightblue', 'Pending', 'card-id-4', 1, 'list-3', NULL, '1627005118377', '', 'card-container-4', '2021-07-28 23:39PM', ''),
(5, 'Card Generated By DB5', 'Card Generated By DB5 description', 'Important', 'darkblue', 'To Do', 'card-id-5', 0, 'list-2', NULL, '1627005118377', '', 'card-container-5', '2021-07-28 23:39PM', ''),
(6, 'Card DB', 'Generated By DB6 description', 'Desgin Team', 'orange', 'Pending', 'card-id-6', 3, 'list-3', NULL, '1627005118377', '', 'card-container-6', '2021-07-28 23:39PM', ''),
(7, 'new card', 'I have some description', 'Help', 'lightblue', 'To Do', 'card-id-7', 1, 'list-2', NULL, '1627005118377', '', 'card-container-7', '2021-07-28 23:39PM', ''),
(8, 'system report', 'add udapte', 'Priority', 'blue', 'Pending', 'card-id-8', 5, 'list-3', NULL, '1627005118377', '', 'card-container-8', '2021-07-28 23:39PM', ''),
(9, 'new', 'Card Generated By DB9 description', 'Important', '', 'Pending', 'card-id-9', 6, 'list-3', NULL, '1627005118377', 'archive_card', 'card-container-9', '2021-07-28 23:39PM', '');

-- --------------------------------------------------------

--
-- Table structure for table `list`
--

CREATE TABLE `list` (
  `id` int(11) NOT NULL,
  `list_order` int(255) DEFAULT NULL,
  `list_createdate` varchar(255) DEFAULT NULL,
  `list_timestamp` varchar(500) DEFAULT NULL,
  `db_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `list_id` varchar(100) NOT NULL,
  `list_title` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `list`
--

INSERT INTO `list` (`id`, `list_order`, `list_createdate`, `list_timestamp`, `db_date`, `list_id`, `list_title`) VALUES
(1, 0, '7/10/2021 8:59 am', '1625900349123', '2021-07-10 06:59:06', 'list-1', 'Board List'),
(2, 1, '7/10/2021 8:59 am', '1625900349123', '2021-07-10 06:59:06', 'list-2', 'To Do'),
(3, 2, '7/10/2021 8:59 am', '1625900349123', '2021-07-10 06:59:06', 'list-3', 'Pending'),
(4, 3, '7/10/2021 8:59 am', '1625900349123', '2021-07-10 06:59:06', 'list-4', 'Done');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `card`
--
ALTER TABLE `card`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `list`
--
ALTER TABLE `list`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `card`
--
ALTER TABLE `card`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT for table `list`
--
ALTER TABLE `list`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
